import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar";
import Sidebar from "../components/sidebar/sidebar";

export const metadata: Metadata = {
  title: "Programmer Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake ">
      <body>
        <Navbar />
        <div className="drawer lg:drawer-open">
          <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex h-[calc(100vh-4rem)] flex-col justify-center overflow-hidden bg-[url('/img/bg.jpg')] bg-cover bg-center">
            {children}
          </div>
          {/* calculate the height of the drawer side prevent overflow */}
          <div className="drawer-side h-[calc(100vh-4rem)]">
            <Sidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
